### ISSUE TITLE
ARM compatibility

### ISSUE THREAD

**Issue by premorion** [MusicGenerator/mumble-ruby-pluginbot-docker#8]
I'm trying to build the bot in a Raspberry Pi but it seems that is not compatible with it.

This is the message I get:
`Step 11/55 : RUN echo "deb http://httpredir.debian.org/debian jessie main contrib non-free" >> /etc/apt/sources.list.d/nonfree.list
 ---> Running in 3a67bd7f71c6
standard_init_linux.go:178: exec user process caused "exec format error"
The command '/bin/sh -c echo "deb http://httpredir.debian.org/debian jessie main contrib non-free" >> /etc/apt/sources.list.d/nonfree.list' returned a non-zero code: 1
`
I'm not too familiar with Docker, but it seems that some minor changes into the script will do the trick.

Thanks!

**Comment by Natenom** [comment]
I don't own any ARM based device where I could do this work. If anyone does feel free to do the work :) 

Closing this.
